services: 
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: waifucollector
      # this mysql database should only be exposed to the other services
      MYSQL_ROOT_PASSWORD: waifu
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql:/var/lib/mysql
    networks:
      - caddy_net
    restart: always

  server:
    build: server/
    expose:
      - "8080"
    depends_on:
      - mysql
    networks:
      - caddy_net

  client:
    build: client/
    expose:
      - "80"
    depends_on:
      - server
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
